version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: gO4AwfIXkp76
      MYSQL_DATABASE: erco_energy
      MYSQL_USER: lucas_kuratani
      MYSQL_PASSWORD: Ad35oA34SqKo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data: