import { BaseSeeder } from '@adonisjs/lucid/seeders'
import { DateTime } from 'luxon'
import Task from '#models/task'

export default class extends BaseSeeder {
  async run() {
    await Task.createMany([
      {
        userId: 1,
        title: 'Implement User Authentication',
        description: 'Develop a secure user authentication system with password hashing.',
        status: 'In Progress',
        priority: 'High',
        completedAt: null,
        createdAt: DateTime.fromISO('2024-11-15T10:00:00Z'),
        updatedAt: DateTime.now(),
      },
      {
        userId: 1,
        title: 'Design Database Schema',
        description: 'Create a relational database schema for the new application.',
        status: 'To Do',
        priority: 'Medium',
        completedAt: null,
        createdAt: DateTime.fromISO('2024-11-14T14:30:00Z'),
        updatedAt: DateTime.now(),
      },
      {
        userId: 1,
        title: 'Write Unit Tests',
        description: 'Develop comprehensive unit tests for the core application logic.',
        status: 'Completed',
        priority: 'High',
        completedAt: DateTime.fromISO('2024-11-23T09:15:00Z'),
        createdAt: DateTime.fromISO('2024-11-13T09:15:00Z'),
        updatedAt: DateTime.fromISO('2024-11-14T11:00:00Z'),
      },
      {
        userId: 1,
        title: 'Refactor Payment Module',
        description: 'Improve the performance and maintainability of the payment module.',
        status: 'In Progress',
        priority: 'Medium',
        completedAt: null,
        createdAt: DateTime.fromISO('2024-11-16T16:45:00Z'),
        updatedAt: DateTime.now(),
      },
      {
        userId: 1,
        title: 'Create API Documentation',
        description: 'Generate comprehensive API documentation using Swagger.',
        status: 'To Do',
        priority: 'Low',
        completedAt: null,
        createdAt: DateTime.fromISO('2024-11-17T11:20:00Z'),
        updatedAt: DateTime.now(),
      },
      {
        userId: 1,
        title: 'Optimize Image Loading',
        description: 'Reduce image loading times on the website.',
        status: 'Completed',
        priority: 'Medium',
        completedAt: DateTime.fromISO('2024-11-18T13:00:00Z'),
        createdAt: DateTime.fromISO('2024-11-12T13:00:00Z'),
        updatedAt: DateTime.fromISO('2024-11-15T15:30:00Z'),
      },
      {
        userId: 1,
        title: 'Implement Search Functionality',
        description: 'Add a search feature to the application.',
        status: 'In Progress',
        priority: 'High',
        completedAt: null,
        createdAt: DateTime.fromISO('2024-11-18T08:00:00Z'),
        updatedAt: DateTime.now(),
      },
      {
        userId: 1,
        title: 'Review Security Vulnerabilities',
        description: 'Conduct a security audit and address identified vulnerabilities.',
        status: 'To Do',
        priority: 'High',
        completedAt: null,
        createdAt: DateTime.fromISO('2024-11-19T17:10:00Z'),
        updatedAt: DateTime.now(),
      },
      {
        userId: 1,
        title: 'Deploy to Production',
        description: 'Deploy the latest version of the application to the production server.',
        status: 'Completed',
        priority: 'High',
        completedAt: DateTime.fromISO('2024-11-18T10:30:00Z'),
        createdAt: DateTime.fromISO('2024-11-11T10:30:00Z'),
        updatedAt: DateTime.fromISO('2024-11-16T12:00:00Z'),
      },
      {
        userId: 1,
        title: 'Create User Interface Mockups',
        description: 'Design mockups for the new user interface features.',
        status: 'To Do',
        priority: 'Medium',
        completedAt: null,
        createdAt: DateTime.fromISO('2024-11-20T12:45:00Z'),
        updatedAt: DateTime.now(),
      },
      {
        userId: 1,
        title: 'Integrate Third-Party API',
        description: 'Integrate a third-party API for data retrieval.',
        status: 'In Progress',
        priority: 'Medium',
        completedAt: null,
        createdAt: DateTime.fromISO('2024-11-17T09:00:00Z'),
        updatedAt: DateTime.now(),
      },
      {
        userId: 1,
        title: 'Write End-to-End Tests',
        description: 'Develop end-to-end tests for critical user flows.',
        status: 'Completed',
        priority: 'High',
        completedAt: DateTime.fromISO('2024-11-24T16:20:00Z'),
        createdAt: DateTime.fromISO('2024-11-14T16:20:00Z'),
        updatedAt: DateTime.fromISO('2024-11-18T14:00:00Z'),
      },
      {
        userId: 1,
        title: 'Improve Error Handling',
        description: 'Enhance error handling throughout the application.',
        status: 'To Do',
        priority: 'Low',
        completedAt: null,
        createdAt: DateTime.fromISO('2024-11-21T15:30:00Z'),
        updatedAt: DateTime.now(),
      },
      {
        userId: 1,
        title: 'Implement Logging System',
        description: 'Set up a centralized logging system for application monitoring.',
        status: 'In Progress',
        priority: 'Medium',
        completedAt: null,
        createdAt: DateTime.fromISO('2024-11-19T11:00:00Z'),
        updatedAt: DateTime.now(),
      },
      {
        userId: 1,
        title: 'Optimize Database Queries',
        description: 'Improve the performance of slow database queries.',
        status: 'Completed',
        priority: 'High',
        completedAt: DateTime.fromISO('2024-11-26T13:45:00Z'),
        createdAt: DateTime.fromISO('2024-11-16T13:45:00Z'),
        updatedAt: DateTime.fromISO('2024-11-20T10:00:00Z'),
      },
      {
        userId: 1,
        title: 'Update Frontend Framework',
        description: 'Upgrade the frontend framework to the latest version.',
        status: 'To Do',
        priority: 'Medium',
        completedAt: null,
        createdAt: DateTime.fromISO('2024-11-22T09:30:00Z'),
        updatedAt: DateTime.now(),
      },
      {
        userId: 1,
        title: 'Create Backup and Restore Procedures',
        description: 'Develop procedures for backing up and restoring application data.',
        status: 'In Progress',
        priority: 'High',
        completedAt: null,
        createdAt: DateTime.fromISO('2024-11-20T18:00:00Z'),
        updatedAt: DateTime.now(),
      },
      {
        userId: 1,
        title: 'Configure CI/CD Pipeline',
        description: 'Set up a continuous integration and continuous delivery pipeline.',
        status: 'In Progress',
        priority: 'High',
        completedAt: null,
        createdAt: DateTime.fromISO('2024-11-24T10:00:00Z'),
        updatedAt: DateTime.now(),
      },
      {
        userId: 1,
        title: 'Implement Feature X',
        description: 'Develop and integrate the new Feature X into the application.',
        status: 'To Do',
        priority: 'Medium',
        completedAt: null,
        createdAt: DateTime.fromISO('2024-11-25T14:30:00Z'),
        updatedAt: DateTime.now(),
      },
      {
        userId: 1,
        title: 'Address Performance Bottlenecks',
        description: 'Identify and resolve performance bottlenecks in the application.',
        status: 'Completed',
        priority: 'High',
        completedAt: DateTime.fromISO('2024-12-01T09:15:00Z'),
        createdAt: DateTime.fromISO('2024-11-20T09:15:00Z'),
        updatedAt: DateTime.fromISO('2024-12-02T11:00:00Z'),
      },
      {
        userId: 1,
        title: 'Integrate Payment Gateway Y',
        description: 'Integrate the new Payment Gateway Y into the system.',
        status: 'Canceled',
        priority: 'Medium',
        completedAt: null,
        createdAt: DateTime.fromISO('2024-11-26T16:45:00Z'),
        updatedAt: DateTime.now(),
      },
      {
        userId: 1,
        title: 'Prepare Release Documentation',
        description: 'Write the release notes and other documentation for the upcoming release.',
        status: 'To Do',
        priority: 'Low',
        completedAt: null,
        createdAt: DateTime.fromISO('2024-11-27T11:20:00Z'),
        updatedAt: DateTime.now(),
      },
      {
        userId: 1,
        title: 'Optimize Asset Delivery',
        description: 'Improve the delivery of static assets (JS, CSS, images).',
        status: 'Canceled',
        priority: 'Medium',
        completedAt: null,
        createdAt: DateTime.fromISO('2024-11-19T13:00:00Z'),
        updatedAt: DateTime.fromISO('2024-11-22T15:30:00Z'),
      },
      {
        userId: 1,
        title: 'Implement Real-time Updates',
        description: 'Add real-time update functionality using WebSockets.',
        status: 'Canceled',
        priority: 'High',
        completedAt: null,
        createdAt: DateTime.fromISO('2024-11-28T08:00:00Z'),
        updatedAt: DateTime.now(),
      },
      {
        userId: 1,
        title: 'Address Accessibility Issues',
        description: 'Resolve any outstanding accessibility issues on the platform.',
        status: 'Canceled',
        priority: 'High',
        completedAt: null,
        createdAt: DateTime.fromISO('2024-11-29T17:10:00Z'),
        updatedAt: DateTime.now(),
      },
      {
        userId: 1,
        title: 'Create Onboarding Flow',
        description: 'Design and implement a new user onboarding flow.',
        status: 'Canceled',
        priority: 'High',
        completedAt: null,
        createdAt: DateTime.fromISO('2024-11-18T10:30:00Z'),
        updatedAt: DateTime.fromISO('2024-11-21T12:00:00Z'),
      },
      {
        userId: 1,
        title: 'Implement Advanced Search',
        description: 'Enhance the search functionality with advanced filtering options.',
        status: 'In Progress',
        priority: 'Medium',
        completedAt: null,
        createdAt: DateTime.fromISO('2024-11-30T12:45:00Z'),
        updatedAt: DateTime.now(),
      },
    ])
  }
}
